//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageFileVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asuser
    {
        public string 索引編號 { get; set; }
        public string 客戶編號 { get; set; }
        public bool chkno { get; set; }
        public string 客戶名稱 { get; set; }
        public string 負責業務 { get; set; }
        public string 區域業務 { get; set; }
        public string 客戶電話 { get; set; }
        public string 客戶電話2 { get; set; }
        public string 分機1 { get; set; }
        public string 分機2 { get; set; }
        public string 附掛1 { get; set; }
        public string 附掛2 { get; set; }
        public string 負責醫師 { get; set; }
        public string 客戶地址 { get; set; }
        public string 軟體購買日 { get; set; }
        public decimal 購買金額 { get; set; }
        public decimal 工作站數 { get; set; }
        public decimal 付費站數 { get; set; }
        public string 硬體購買日 { get; set; }
        public decimal 維護方式 { get; set; }
        public string 維護起始日 { get; set; }
        public string 維護到期日 { get; set; }
        public string 維護入帳日 { get; set; }
        public string 計次版本 { get; set; }
        public string 目前版本 { get; set; }
        public string 更版日期 { get; set; }
        public string 目前版次 { get; set; }
        public decimal 合約金額 { get; set; }
        public string 合約備註 { get; set; }
        public decimal 合約種類 { get; set; }
        public byte xml安裝 { get; set; }
        public string xml已安裝 { get; set; }
        public byte xml安裝台 { get; set; }
        public byte HCA { get; set; }
        public byte HCA2 { get; set; }
        public bool 寄合約 { get; set; }
        public string 縣市 { get; set; }
        public string 郵遞區號 { get; set; }
        public string 畢業學校 { get; set; }
        public string 聯絡人 { get; set; }
        public string 醫事代號 { get; set; }
        public decimal 等級 { get; set; }
        public string 備註 { get; set; }
        public string 更版密碼 { get; set; }
        public string 註冊密碼 { get; set; }
        public string 舊版密碼 { get; set; }
        public string 看診時段 { get; set; }
        public string 申報方式 { get; set; }
        public string 快速碼 { get; set; }
        public string 介紹 { get; set; }
        public string 轉檔 { get; set; }
        public string EMAIL { get; set; }
        public string FOX版本 { get; set; }
        public string 影像碼 { get; set; }
        public string 行動電話 { get; set; }
        public string 安裝人員 { get; set; }
        public string 成交人員 { get; set; }
        public string 傳真 { get; set; }
        public string 統編 { get; set; }
        public string 統編抬頭 { get; set; }
        public string 讀卡機 { get; set; }
        public int 讀卡機數量 { get; set; }
        public bool IC卡教學 { get; set; }
        public string VPN_IP { get; set; }
        public string 硬體到期日 { get; set; }
        public bool 光碟更版 { get; set; }
        public bool 自安讀卡機 { get; set; }
        public string 登錄日期 { get; set; }
        public string 防毒到期日 { get; set; }
        public int 申報時段 { get; set; }
        public string 遠端維護 { get; set; }
        public string 遠端維護2 { get; set; }
        public int PORT { get; set; }
        public string CPORT1 { get; set; }
        public string CPORT2 { get; set; }
        public string CPORT3 { get; set; }
        public string CPORT4 { get; set; }
        public string VPN備註 { get; set; }
        public string 帳款聯絡人 { get; set; }
        public string 收款方式 { get; set; }
        public string 公會頭銜 { get; set; }
        public decimal 合約等級 { get; set; }
        public decimal 客戶等級 { get; set; }
        public string 客戶區域 { get; set; }
        public string 新影像碼 { get; set; }
        public string EMR碼 { get; set; }
        public string 客戶類別 { get; set; }
        public string 負責單位 { get; set; }
        public string 使用狀況 { get; set; }
        public string 體系名稱 { get; set; }
        public int 巷 { get; set; }
        public int 弄 { get; set; }
        public int 鄰 { get; set; }
        public int 之號 { get; set; }
        public int 號 { get; set; }
        public int 之 { get; set; }
        public int 樓 { get; set; }
        public string 路 { get; set; }
        public string 里 { get; set; }
        public bool 不訪查 { get; set; }
        public string 超商代號 { get; set; }
        public string AUPD { get; set; }
        public string QUPD { get; set; }
        public string sarea { get; set; }
        public string @checked { get; set; }
        public int ASEQ { get; set; }
        public int IKEY { get; set; }
        public string 台中索編 { get; set; }
        public string 台中客編 { get; set; }
        public string 台中名稱 { get; set; }
        public string 台中備註 { get; set; }
        public string 關連索編 { get; set; }
        public string 別名 { get; set; }
        public string 高雄索編 { get; set; }
        public int skey { get; set; }
        public string 關連索編2 { get; set; }
        public string 關連索編3 { get; set; }
        public string 關連索編4 { get; set; }
        public string 關連索編5 { get; set; }
        public string 別名2 { get; set; }
        public string 別名3 { get; set; }
        public string 別名4 { get; set; }
        public string 別名5 { get; set; }
        public string 所屬工程 { get; set; }
        public string 所屬客服 { get; set; }
        public string 版本s { get; set; }
        public string 憑證預約日 { get; set; }
        public string 憑證安裝日 { get; set; }
        public string 線上申請3 { get; set; }
        public string gip1 { get; set; }
        public string gip2 { get; set; }
        public string 線上申請4 { get; set; }
        public string 線上申請5 { get; set; }
        public string 線上申請6 { get; set; }
        public string 線上申請7 { get; set; }
        public string 線上申請8 { get; set; }
        public string 線上申請9 { get; set; }
        public string 授權 { get; set; }
    }
}
