//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageFileVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bug_notice
    {
        public int ikey { get; set; }
        public int announcement_ikey { get; set; }
        public string uid { get; set; }
        public string 回報結果 { get; set; }
        public string 測試檔案 { get; set; }
        public int 測試類別 { get; set; }
        public string 診所索引編號 { get; set; }
        public string 版本 { get; set; }
        public Nullable<System.DateTime> 預計完成日 { get; set; }
        public Nullable<int> 退回 { get; set; }
        public Nullable<int> 需討論 { get; set; }
        public Nullable<System.DateTime> 完成日 { get; set; }
        public Nullable<System.DateTime> 建立日期 { get; set; }
        public Nullable<System.DateTime> 修改時間 { get; set; }
        public string 最後狀態 { get; set; }
        public string 備註 { get; set; }
        public Nullable<int> 回報等級 { get; set; }
    }
}
