//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageFileVersion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class I_cpnewsEntities : DbContext
    {
        public I_cpnewsEntities()
            : base("name=I_cpnewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<servfile> servfile { get; set; }
        public virtual DbSet<test_notice> test_notice { get; set; }
        public virtual DbSet<servfile_notice> servfile_notice { get; set; }
        public virtual DbSet<bug_type> bug_type { get; set; }
        public virtual DbSet<bug_notice> bug_notice { get; set; }
    }
}
