//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageFileVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servfile_notice
    {
        public string 檔名 { get; set; }
        public string 版本 { get; set; }
        public Nullable<System.DateTime> 更新日期 { get; set; }
        public string 類別 { get; set; }
        public string 顯示檔名 { get; set; }
        public string 存放路徑 { get; set; }
        public int Skey { get; set; }
    }
}
