//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageFileVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servfile
    {
        public string 檔名 { get; set; }
        public string 版本 { get; set; }
        public int 大小 { get; set; }
        public string 檔案路徑 { get; set; }
        public string 副檔名 { get; set; }
        public bool 影像檔 { get; set; }
        public bool 外掛檔 { get; set; }
        public string 原檔名 { get; set; }
        public string 安裝位置 { get; set; }
        public bool dn1 { get; set; }
        public int crc { get; set; }
        public string crc32 { get; set; }
        public string md5 { get; set; }
        public int lcrc { get; set; }
        public string lcrc32 { get; set; }
        public string lmd5 { get; set; }
        public string specialchk { get; set; }
        public int isnewonly { get; set; }
        public string pdt { get; set; }
        public int Skey { get; set; }
    }
}
