//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageFileVersion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_notice
    {
        public int ikey { get; set; }
        public string 檔案名稱 { get; set; }
        public string 版本 { get; set; }
        public System.DateTime 修改日期 { get; set; }
        public string 主旨 { get; set; }
        public string 測試文件路徑 { get; set; }
        public string 測試檔案路徑 { get; set; }
        public string 產品類別 { get; set; }
        public int 釋出正式版 { get; set; }
    }
}
